services:
  dev-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
    ports:
      - "8000:8000"
      - "4000:4000"
    networks:
      - payment-processor
networks:
  payment-processor:
    external: true